Fix members.fetch to use user ID instead of User object
In Discord.js v14, GuildMemberManager.fetch() requires a user ID string,
not a User object. Changed msg.author to msg.author.id on line 30.

This fixes the "Unknown User" error that occurred when the custom spam
filter tried to fetch members that weren't in the cache.

Error: DiscordAPIError[10013]: Unknown User